### ISSUE TITLE
Is this in any way compatible with Cordova?

### ISSUE THREAD

**Issue by kmgsoftware** [timothyekl/BootLaunch#1]
Trying to get an html5-based (Ionic) app to autostart on iOS. Is this possible?

**Comment by timothyekl** [comment]
Hmm, I'm not familiar enough with Ionic to say for sure. Presumably, though, the produced app still has an Info.plist, in which you could specify the appropriate key.

Keep in mind, though, that you really shouldn't use this project as a how-to for getting arbitrary apps to autostart. The Info.plist key in question is designated specifically for VoIP apps, so unless you're building one of those, probably better to let iOS manage the lifetime of the app as usual.
